spring.application.name=OAuth-login
#Github Login
spring.security.oauth2.client.registration.github.client-id=v23liFJHGIesptNoKjx
spring.security.oauth2.client.registration.github.client-secret=2af5e2d8583de2f23da7ba0f6089595782a26545

#Google Login

logging.level.org.springframework.security=TRACE
